### ISSUE TITLE
Things missing from v2

### ISSUE THREAD

**Issue by WorldLanguages** [WorldLanguages/ScratchNotifier#1]
- [x] Overview
- [x] Subscribe to OneSignal automatically
- [x] Privacy page
- [x] Add link to repo in footer

**Comment by locness3** [comment]
OneSignal ? Also, what was overview @WorldLanguages

**Comment by WorldLanguages** [comment]
@locness3 
Overview was on Scratch Notifier v2 a series of sweetalerts you received when you used it for the first time telling you how to use it, to keep the tab pinned, etc.
OneSignal is a push notification service that I can use to notify users if I need to without having to literally add Javascript code to do that.
