### ISSUE TITLE
Remove underline from links

### ISSUE THREAD

**Issue by locness3** [WorldLanguages/ScratchNotifier#4]
This makes it look cleaner. Maybe add a background color on hover too ?

**Comment by WorldLanguages** [comment]
I will think about it.
I added the underline when this Scratch Notifier version was going to have something similar to isOnline as a sidebar. Back then, not all black text was clickable. Now that's different.

**Comment by locness3** [comment]
Doing a pull maybe

**Comment by WorldLanguages** [comment]
@locness3 Please confirm if you want to work on this?

**Comment by locness3** [comment]
> @locness3 Please confirm if you want to work on this?

Yes, tomorrow (It's Saturday 9 February 20:12 when writing this, in France)

**Comment by locness3** [comment]
Sunday, 8:43. Let's go. Cloning the repo.

**Comment by locness3** [comment]
@WorldLanguages see #11
