### ISSUE TITLE
ANNOYING BUG : It sends way too much notifications

### ISSUE THREAD

**Issue by locness3** [WorldLanguages/ScratchNotifier#6]
I had 1 unread message, it sent approximately 15 notifications at the same time!
![way too much notifications screenshot](https://user-images.githubusercontent.com/37651007/52522612-eecb0380-2c87-11e9-8bfb-b4bbb093db4e.png)
Firefox 65.0, macOS 10.11.6 El Capitan

**Comment by locness3** [comment]
@WorldLanguages

**Comment by WorldLanguages** [comment]
Wow that's weird!
I don't know what is causing it tho, take a look at this line: https://github.com/WorldLanguages/ScratchNotifier/blob/master/notifier.js#L115
It only sends the notification if `msgCount > oldMsgCount`, and `oldMsgCount` is the value of the global variable `msgCount` before checking the message count again.
Unless Firefox for some reason decided to trigger `checkMainMessages()` many times at once for some reason, I have no idea what can cause this.

**Comment by locness3** [comment]
It didn't did after. My computer was sleeping, maybe it has impacted it ?

**Comment by locness3** [comment]
@WorldLanguages

**Comment by WorldLanguages** [comment]
@locness3 That's probably it. I'll make a fix soon.

**Comment by WorldLanguages** [comment]
This should be fixed with commit e66cfc1
`checkMainMessages()` now can only run if it hasn't been called in the last 5 seconds (and if that call was ran too).
@locness3 Would be helpful if you told me if this happens with alt accounts too. I don't know why it wouldn't, tho.

**Comment by locness3** [comment]
Huh, none of my alt accounts recieves messaages, lol

**Comment by WorldLanguages** [comment]
@locness3 Fixed, stupid bug because of something I modified the day of the release... Make sure to have the bell enabled for that alt of course, if you want to test this

**Comment by locness3** [comment]
You should unassign you so
